spring.application.name=jammee
spring.config.import=file:env.properties
# SERVER CONFIG
server.port=3001
# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/${PG_DB_NAME}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
# JWT CONFIG
jwt.secret=${JWT_SECRET}
# CLOUDINARY CONFIG
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.key=${CLOUDINARY_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
# MAILGUN
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.apiKey=${MAILGUN_KEY}